{% set name = "PyMetis" %}
{% set version = "2025.2.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name | lower }}-{{ version }}.tar.gz
  sha256: 0ce7b71e8f905293a809fd2da90248f9f2197ff40286dcba4cc835270142baf5

build:
  number: 3
  skip: true  # [py<310]
  script:
    # Need to parse MESON_ARGS to make sure meson finds the correct executables for cross-compilation.
    - echo "python = '${BUILD_PREFIX}/bin/python'" >> ${BUILD_PREFIX}/meson_cross_file.txt
    - $PYTHON -m build -w -n -x -Csetup-args=${MESON_ARGS// / -Csetup-args=} -Csetup-args="-Duse-shipped-metis=false"     # [unix]
    - $PYTHON -m pip install dist/pymetis*.whl                                                                            # [unix]
    - python -m pip install . -vv -Csetup-args="-Duse-shipped-metis=false"                                                # [win]

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - pybind11                               # [build_platform != target_platform]
    - ninja                                  # [build_platform != target_platform]
    - meson-python                           # [build_platform != target_platform]
    - {{ stdlib("c") }}
    - {{ compiler('cxx') }}
    - metis                                  # [build_platform != target_platform]
  host:
    - python
    - python-build
    - pip
    - pybind11
    - meson-python
    - metis
  run:
    - typing_extensions >=4.5
    - python
    - metis

test:
  imports:
    - pymetis  # [build_platform == target_platform]
  requires:
    - pip
    - pytest
    - numpy
    - metis
    - meshpy  # [unix and x86_64]
  source_files:
    - test
  commands:
    - pip check
    # There were some test failures on Windows, but life is too short to debug them. :shrug:
    - cd test && python -m pytest  # [unix and build_platform == target_platform]
    - ls $SP_DIR/pymetis/*         # [build_platform != target_platform]
    
about:
  home: https://github.com/inducer/pymetis
  summary: A Graph Partitioning Package
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - inducer
