{% set name = "PyMetis" %}
{% set version = "2025.1.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name | lower }}-{{ version }}.tar.gz
  sha256: c02bf0fdd9483ff9dac031c73219ab9aa7a90e110f09d3c00f1799f334d813d8

build:
  number: 0
  skip: true  # [py<310]
  script:
    # Need to parse MESON_ARGS to make sure meson finds the correct executables for cross-compilation.
    - $PYTHON -m build -w -n -x -Csetup-args=${MESON_ARGS// / -Csetup-args=}    # [unix]
    - $PYTHON -m pip install dist/meshpy*.whl                                   # [unix]
    - python -m pip install . -vv                                               # [win]

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - numpy                                  # [build_platform != target_platform]
    - pybind11                               # [build_platform != target_platform]
    - ninja                                  # [build_platform != target_platform]
    - meson-python                           # [build_platform != target_platform]
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - {{ compiler('cxx') }}
  host:
    - python
    - pytho-build
    - pip
    - metis
    - pybind11
    - meson-python
  run:
    - numpy
    - python
    - metis

test:
  imports:
    - pymetis
  requires:
    - pip
    - pytest
    - numpy
    - metis
    - meshpy  # [unix and x86_64]
  source_files:
    - test
  commands:
    - pip check
    - cd test && python -m pytest

about:
  home: https://github.com/inducer/pymetis
  summary: A Graph Partitioning Package
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - inducer
